### ISSUE TITLE
Prepare ER diagram and create the database (MS SQL, but not mandatory - only important to be able to integrate to your solution).

### ISSUE THREAD

**Issue by disoversity** [bamboozlegui/Karma#39]

**Comment by karoluzas** [comment]
We have databases created so I believe only thing that's left is the ER diagram. I could probably tackle this requirement.

**Comment by disoversity** [comment]
If I correctly interpreted our lecturer's statement - this requirement is a little bit outdated and does not strictly require ER diagram, meaning that creating the database should suffice... and as you know - we already created one long time ago.

Although, we should ask our lecturer once again, because in my mind it sounds too good to be true :D

**Comment by karoluzas** [comment]
Well regardless, in kimutis.lt such requirement still exists so it should be treated as a requirement, but asking our lecturer about it wouldn't hurt too I guess

**Comment by karoluzas** [comment]
Tried making the ER diagram, got a bit confused tho.
We have a lot of unused databases. ASP.NET created these when I made accounts but they dont seem to be doing anything so I didn't include them in this diagram because I dont know how they interact with each other.
![paveikslas](https://user-images.githubusercontent.com/79944650/144283940-6c545b9b-3cb2-4f35-abb8-cff591c26893.png)

The message table as well, I'm not quite sure i did the relationships the right way, need some feedback @disoversity 

Here is the diagram
![Karma ER diagram first iteration](https://user-images.githubusercontent.com/79944650/144284192-5df52ec8-3cfb-4357-9693-6d46c13d4393.png)
:

**Comment by karoluzas** [comment]
Thanks for the feedback, what you think about this @bamboozlegui

**Comment by disoversity** [comment]
Apologies @karoluzas. I don't know know I missed this comment...
I thought that showing those ASP.NET generated tables was not as mandatory, so I think it was ok skipping them and showing our explicit tables. I think you did a very good job representing our simple database.

**Comment by bamboozlegui** [comment]
> Thanks for the feedback, what you think about this @bamboozlegui

@karoluzas - me + databases throws an exception, other than that, nice painting!

**Comment by karoluzas** [comment]
> @karoluzas - me + databases throws an exception, other than that, nice painting!

What do you mean :D
