### ISSUE TITLE
Logging to the file or server of most important logic

### ISSUE THREAD

**Issue by disoversity** [bamboozlegui/Karma#45]

**Comment by bamboozlegui** [comment]
The satus code (when user tries to post or request item) of the httprequest seems to be quite important, because if the user experiences any problems when posting, we can easily check what went wrong there.

I'd be interested to know what you deem to be important and in need of logging in the context of our project, @disoversity and @karoluzas.

**Comment by karoluzas** [comment]
Well I'd say we definitely should log posting and problems that may arise. But you don't really touch on what else we can log, in regard to the second paragraph, so can't really answer your question :D

Awesome that you're working on this, knew you was workin on things in the background

**Comment by disoversity** [comment]
@bamboozlegui I think basic things like User X added Item Y successfully and User X submitted request Y could be one of the things, but probably you had this in mind in your first paragraph.
Basically logging every service in some way. Albeit our messaging/notifying, repository services etc., since most of our logic reside there.

**Comment by bamboozlegui** [comment]
Thanks guys, I appreciate your input!
